### ISSUE TITLE
King can't move out of check?

### ISSUE THREAD

**Issue by HerrSchreiber** [gradysocool/Senior-Project#10]
This sequence causes the program to say it's an illegal move:

1.e4 e5 2.Nf3 Nc6 3.Bb5 a6 4.Ba4 Nf6 5.O-O b5 6.Bb3 Be7 7.d4 d6 8.dxe5 dxe5
9.Qe2 Nd4 10.Nxd4 Qxd4 11.c3 Qb6 12.Kh1 O-O 13.Nd2 Bb7 14.Bc2 c5 15.Re1 Rfd8
16.Nf1 Rd7 17.Ng3 g6 18.f4 exf4 19.Bxf4 Qe6 20.Rf1 Rad8 21.Rae1 Qg4 22.Qf2 Nh5
23.Nxh5 Qxh5 24.Bg3 f6 25.Bf4 Qg4 26.e5 fxe5 27.Bh6 Qe6 28.Qg3 e4 29.Bd1 Rd3
30.Bg4 Qd6 31.Qf2 Qe5 32.Qf7 Kh8

**Comment by gradysocool** [comment]
Also 29...Rd3 outputted "Invalid Move". I had to instead write R7d3 to make the move. I think the other rook is messing it up.

**Comment by gradysocool** [comment]
That's interesting. I wrote it to output "White wins by checkmate" if it is in check and cannot find a valid move even.

**Comment by gradysocool** [comment]
well that's a quick fix. turns out I completely forgot about kingSquareWhite and kingSquareBlack. 
The moves 1. e4 e5 2. Bb5 Bb4 3. a3 Kf8 4. a4 d6 more easily demonstrates the problem.

**Comment by gradysocool** [comment]
Wow, and the checkmate doesn't appear for a completely different reason...The king can block it's own check to the previous square haha

**Comment by gradysocool** [comment]
All problems discussed here are fixed.
