### ISSUE TITLE
kingSquare performance

### ISSUE THREAD

**Issue by HerrSchreiber** [gradysocool/Senior-Project#3]
Rather than checking all the squares to find where the king of a certain color is, just store 4 variables: whiteKingRank, whiteKingFile, blackKingRank, blackKingFile, or you can just store 2 square variables. It'll make things run much faster if you have to check where the kings are often.

Just make sure that you change the variables when the king moves.

**Comment by gradysocool** [comment]
Good point, this might bottleneck if I have to use all squares, since this method is called a lot
